server:
  port: 8090
spring:
  application:
    name: jee-love
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jee-love?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=yes
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/*/*.xml

