server:
  port: 8090
spring:
  application:
    name: jee-love
  datasource:
    url: jdbc:mysql://111.231.74.237:3306/jee_love?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=yes
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/*/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

