server:
  port: 8090
spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: jee-love
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jee_love?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=yes
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath*:/mapper/*/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
